version: '3.8'
services:
  api-gw-co:
    image: api-gw-co:latest
    ports:
      - "8080:8080"
    depends_on:
      - shopping-cart
      - product-service
    environment:
      SHOPPING_CART_URL: http://shopping-cart:8081
      PRODUCT_SERVICE_URL: http://product-service:8082

  shopping-cart:
    image: shopping-cart:latest
    ports:
      - "8081:8080"

  product-service:
    image: product-service:latest
    ports:
      - "8082:8080"
