server:
  port: 8082

spring:
  application:
    name: shoppingcart-service
  datasource:
    url: jdbc:h2:mem:shoppingcart
    driverClassName: org.h2.Driver
    username: sa
    password:  # (blank password by default for H2)

  # Hibernate settings
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/